name: Test

on:
  push:
    branches:
      - main


jobs:
  Hello:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Checking directory
      run: ls -lah

    - name: Checking secret
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
      run: |
        echo "$SSH_KEY" >> ssh-key.pem
        chmod 400 ssh-key.pem

    - name: Copy to server
      run: scp -i ssh-key.pem -o StrictHostKeyChecking=no welcome.txt ubuntu@13.233.212.49:./

    - name: SSH to server
      run: ssh -i ssh-key.pem -o StrictHostKeyChecking=no ubuntu@13.233.212.49 "sudo ls -lah"

