name: Test

on:
  push:
    branches:
      - main


jobs:
  Hello:
   runs-on: ubuntu-latest
   steps:
    - name: step 1
      run: echo "hello1"

    - name: step 2
       run: echo "hello2"

    - name: step 3
       run: echo "hello 3"