name : test

on:
  push:
    branches:
      - main


jobs:
  Hello:
    runs-on: ubuntu-latest
    steps:
      - name: hello msg
        run: echo "hello"

    steps:
      - name: hello 2nd msg
        run: echo "jai mata di"